import json
import os
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True, slots=True)
class RadioRuntimeConfig:
    """Radio settings generated by the POWDER profile."""

    role: str
    radio_type: str
    device_args: str
    center_frequency: float


def load_radio_runtime_config(
    path: str | Path | None = None,
) -> RadioRuntimeConfig:
    """Load this node's radio settings."""

    if path is None:
        path = os.environ.get(
            "POWDER_OTFS_RADIO_CONFIG",
            Path.home()
            / "powder-otfs"
            / ".powder-radio.json",
        )

    config_path = Path(path).expanduser()

    if not config_path.exists():
        raise FileNotFoundError(
            "Radio configuration was not found at "
            f"{config_path}. Run this program on a node "
            "created by the POWDER-OTFS profile."
        )

    with config_path.open(encoding="utf-8") as file:
        values = json.load(file)

    radio_type = str(values["radio_type"]).lower()
    if radio_type not in {"x310", "b210"}:
        raise ValueError(
            "radio_type must be 'x310' or 'b210'."
        )

    return RadioRuntimeConfig(
        role=str(values["role"]),
        radio_type=radio_type,
        device_args=str(values["device_args"]),
        center_frequency=float(
            values["center_frequency"]
        ),
    )
